import re


def normalize_markdown(text: str) -> str:
    """Normalize markdown generated by crawl4ai"""
    text = re.sub(r'\r\n?', '\n', text)                     # Normalize line endings
    text = re.sub(r'\n\s*\n', '\n', text)                   # Collapse multiple blank lines
    text = re.sub(r'[ \t]+', ' ', text)                     # Collapse multiple spaces/tabs
    text = re.sub(r'\n+', '\n', text)                       # Collapse multiple newlines again
    text = re.sub(r'^\s*', '', text, flags=re.MULTILINE)    # strip leading line whitespace
    text = re.sub(r'\s*$', '', text, flags=re.MULTILINE)    # strip trailing line whitespace
    text = re.sub(r'\*\*', '', text)                        # Remove bold
    text = re.sub(r'^\s*\*', '-', text, flags=re.MULTILINE) # Normalize bulletpoint
    text = re.sub(r'\*', '', text)                          # Remove italics
    return text